# Generated by Django 4.2.3 on 2023-08-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('Sneakers', 'Sneakers'), ('Loafer', 'Loafer'), ('Brogue shoe', 'Brogue shoe'), ('sport', 'sport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('black', 'black'), ('white', 'white'), ('blue', 'blue')], max_length=20),
        ),
    ]
